language: generic 
sudo: required

services:
  - docker



before_install:
  - docker build -t andrzejsimin/react-test -f Dockerfile.dev ./client/Dockerfile.dev


script:
  - docker run -e CI=true andrzejsimin/react-test npm run test

after_success:
  - docker build -t andrzejsimin/multi-client ./client
  - docker build -t andrzejsimin/multi-nginx ./nginx
  - docker build -t andrzejsimin/multi-server ./server
  - docker build -t andrzejsimin/multi-worker ./worker
  