language: generic 
sudo: required

services:
  - docker



before_install:
  - docker build -t andrzejsimin/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true andrzejsimin/react-test npm run test

after_success:
  - docker build -t andrzejsimin/multi-client ./client
  - docker build -t andrzejsimin/multi-nginx ./nginx
  - docker build -t andrzejsimin/multi-server ./server
  - docker build -t andrzejsimin/multi-worker ./worker 
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push andrzejsimin/multi-client
  - docker push andrzejsimin/multi-nginx
  - docker push andrzejsimin/multi-server
  - docker push andrzejsimin/multi-worker

  
deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-751112318862'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
